### ISSUE TITLE
White Screen after update 5.0.5

### ISSUE THREAD

**Issue by vnwds** [gndev/shortcodes-ultimate#83]
Hi!

Unfortunately, the update to 5.0.5 produces a white screen for me. I deactivated the plugin, and the page usually loads again. Are there any possible solutions?

Thanks!

**Comment by gndev** [comment]
Hi @vnwds,

please enable WP_DEBUG and post errors here.

How to enable WP_DEBUG:
1. Open `/wp-config.php` file in a text editor;
2. Add the following snippet in the beginning:

```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', true );
```

Thank you!

**Comment by vnwds** [comment]
Sure, I hope this helps.

Thanks!

[19-Sep-2018 13:42:39 UTC] PHP Deprecated:  Function create_function() is deprecated in /is/htdocs/wp12821633_6UYRGJW3IY/www/volleynetwork.com/vnwe/wp-content/plugins/baw-login-logout-menu/bawllm.php on line 13
[19-Sep-2018 13:42:39 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; divi_switch_settings has a deprecated constructor in /is/htdocs/wp12821633_6UYRGJW3IY/www/volleynetwork.com/vnwe/wp-content/plugins/divi-switch/divi-switch.php on line 108
[19-Sep-2018 13:42:40 UTC] PHP Deprecated:  Function create_function() is deprecated in /is/htdocs/wp12821633_6UYRGJW3IY/www/volleynetwork.com/vnwe/wp-content/plugins/page-scroll-to-id/includes/class-malihu-pagescroll2id-widget.php on line 58
[19-Sep-2018 13:42:40 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_page_permastruct() on null in /is/htdocs/wp12821633_6UYRGJW3IY/www/volleynetwork.com/vnwe/wp-includes/link-template.php:357
Stack trace:
#0 /is/htdocs/wp12821633_6UYRGJW3IY/www/volleynetwork.com/vnwe/wp-includes/link-template.php(320): _get_page_link(Object(WP_Post), false, false)
#1 /is/htdocs/wp12821633_6UYRGJW3IY/www/volleynetwork.com/vnwe/wp-includes/link-template.php(144): get_page_link(Object(WP_Post), false, false)
#2 /is/htdocs/wp12821633_6UYRGJW3IY/www/volleynetwork.com/vnwe/wp-content/plugins/memberpress/app/lib/MeprUtils.php(1752): get_permalink(Object(WP_Post), false)
#3 /is/htdocs/wp12821633_6UYRGJW3IY/www/volleynetwork.com/vnwe/wp-content/plugins/memberpress/app/models/MeprOptions.php(808): MeprUtils::get_permalink(212936)
#4 /is/htdocs/wp12821633_6UYRGJW3IY/www/volleynetwork.com/vnwe/wp-content/plugins/memberpress/app/controllers/MeprLoginCtrl.php(224): MeprOptions->login_page_url()
#5 /is/htdocs/wp12821633_6UYRGJW3IY/www/volleynetwork.com/vnwe/wp-i in /is/htdocs/wp12821633_6UYRGJW3IY/www/volleynetwork.com/vnwe/wp-includes/link-template.php on line 357

**Comment by vnwds** [comment]
Ok, thanks for checking the error message.

What options are there to solve the problem? Before the update, Memberpress did not show any compatibility issues, and I can not dispense with using Memberpress. Is there a way to downgrade the plugin? Or other alternatives?

Thanks again!

**Comment by gndev** [comment]
I'm unable to test compatibility with MemberPress because it's a paid plugin, and I do not have a license. Please contact its developer.

You can download previous versions of SU [here](https://wordpress.org/plugins/shortcodes-ultimate/advanced/#download-previous-link). I do not recommend doing this.

**Comment by gndev** [comment]
There is another user experiencing the similar problem: https://wordpress.org/support/topic/getting-error-after-upgrading-from-5-0-4-to-5-0-5/

**Comment by gndev** [comment]
The error isn't triggering if I comment `wp_login_url()` call in `includes/shortcodes/members.php:25`. I continue my investigation.

**Comment by gndev** [comment]
Upgrade to 5.0.6

**Comment by vnwds** [comment]
Thank you very much for the quick fix!

**Comment by gndev** [comment]
Thank you for the detailed report :)
